# BASIC INFORMATION >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
info:
  title: radishzz's blog
  author: radishzz
  url: https://radishzz.cc
# BASIC INFORMATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# IMAGE CONFIGURATION >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
defaults:
  favicon: https://cdn.radishzz.cc/gh/radishzzz/picgo-image@main/000-avatar.webp
  logo:
  avatar: https://cdn.radishzz.cc/gh/radishzzz/picgo-image@main/000-avatar.webp
# IMAGE CONFIGURATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# COLORS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
colors:
  primary: "#5BDFEB"
  secondary:
  default_mode: light
# COLORS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# SITE CUSTOMIZATION >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
global:
  fonts:
    chinese:
      enable: false
      family:
      url:
    english:
      enable: false
      family:
      url:
    title:
      enable: false
      family:
      url:
  content_max_width: 1000px
  sidebar_width: 210px
  hover:
    shadow: true
    scale: false
  scroll_progress:
    bar: false
    percentage: true
  website_counter:
    url: https://cn.vercount.one/js
    enable: true
    site_pv: true
    site_uv: true
    post_pv: true
  single_page: true
  preloader:
    enable: false
    custom_message:
  open_graph: true
  google_analytics:
    enable: false
    id:
# SITE CUSTOMIZATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end
    

# FONTAWESOME >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
fontawesome:
  thin: false
  light: false
  duotone: false
  sharp_solid: false
# FONTAWESOME <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# HOME BANNER >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
home_banner:
  enable: true
  style: fixed
  image:
    light: https://cdn.radishzz.cc/gh/radishzzz/picgo-image@main/000-wallpaper-light.webp
    dark: https://cdn.radishzz.cc/gh/radishzzz/picgo-image@main/000-wallpaper-dark.webp
  title: radishzz's blog
  subtitle:
    text: []
    hitokoto:
      enable: false
      show_author: false
      api: https://v1.hitokoto.cn
    typing_speed: 100
    backing_speed: 80
    starting_delay: 500
    backing_delay: 1500
    loop: true
    smart_backspace: true
  text_color:
    light: "#343A3C"
    dark: "#CBCBD0"
  text_style:
    title_size: 2.8rem
    subtitle_size: 1.5rem
    line_height: 1.2
  custom_font:
    enable: false
    family:
    url:
  social_links:
    enable: true
    style: default
    links:
      github: https://github.com/radishzzz
      telegram: https://t.me/radishzz
      [fontawesome fa-solid fa-square-rss]: /atom.xml
    qrs:
      weixin:
# HOME BANNER <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# NAVIGATION BAR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
navbar:
  auto_hide: false
  color:
    left: "#f78736"
    right: "#367df7"
    transparency: 35
  width:
    home: 1200px
    pages: 1000px
  links:
    Home:
      path: /
      icon: fa-regular fa-house
    Archives:
      path: /archives
      icon: fa-regular fa-archive
    Links:
      icon: fa-regular fa-link
      submenus:
        Friends: /links/
        Gallery: /masonry/
        Status: https://status.radishzz.cc/
  search:
    enable: true
    preload: true
# NAVIGATION BAR <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# HOME PAGE ARTICLE SETTINGS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
home:
  sidebar:
    enable: true
    position: left
    first_item: info
    announcement: (´・ω・´)
    show_on_mobile: true
    links:
      Tags:
        path: /tags
        icon: fa-regular fa-tag
      Categories:
        path: /categories
        icon: fa-regular fa-folder
  article_date_format: YYYY-MM-DD
  excerpt_length: 200
  categories:
    enable: true
    limit: 3
  tags:
    enable: true
    limit: 3
# HOME PAGE ARTICLE SETTINGS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# ARTICLE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
articles:
  style:
    font_size: 16px
    line_height: 1.5
    image_border_radius: 14px
    image_alignment: center
    image_caption: false
    link_icon: true
    title_alignment: left
    headings_top_spacing:
      h1: 3.2rem
      h2: 2.4rem
      h3: 1.9rem
      h4: 1.6rem
      h5: 1.4rem
      h6: 1.3rem
  word_count:
    enable: true
    count: true
    min2read: true
  author_label:
    enable: false
    auto: false
    list: []
  code_block:
    copy: true
    style: mac
    highlight_theme:
      light: github
      dark: vs2015
    font:
      enable: false
      family:
      url:
  toc:
    enable: true
    max_depth: 4
    number: false
    expand: true
    init_open: true
  copyright:
    enable: true
    default: cc_by_nc_sa
  lazyload: false
  recommendation:
    enable: false
    title: 推荐阅读
    limit: 3
    mobile_limit: 2
    placeholder: /images/wallhaven-wqery6-light.webp
    skip_dirs: []
# ARTICLE <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# COMMENT >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
comment:
  enable: true
  system: waline
  config:
    waline:
      serverUrl: https://comment.radishzz.cc
      lang: zh-CN
      emoji: ['//unpkg.com/@waline/emojis@1.2.0/bmoji',
      '//unpkg.com/@waline/emojis@1.2.0/weibo']
      recaptchaV3Key: wasd
      turnstileKey:
      reaction: false
    gitalk:
      clientID:
      clientSecret:
      repo:
      owner:
      proxy:
    twikoo:
      version: 1.6.10
      server_url:
      region:
    giscus:
      repo:
      repo_id:
      category:
      category_id:
      mapping: pathname
      strict: 0
      reactions_enabled: 1
      emit_metadata: 0
      lang: en
      input_position: bottom
      loading: lazy
# COMMENT <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# FOOTER >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
footer:
  runtime: true
  icon: '<i class="fa-solid fa-fan fa-spin fa-spin-reverse" style="color: #f54545"></i>'
  start: 2024/3/22 12:00:00
  statistics: true
  customize:
  icp:
    enable: false
    number:
    url:
# FOOTER <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# INJECT >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
inject:
  enable: false
  head:
    -
  footer:
    -
# INJECT <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# PLUGINS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
plugins:
  feed:
    enable: false
  aplayer:
    enable: false
    type: fixed
    audios:
      - name:
        artist:
        url:
        cover:
        lrc:
  mermaid:
    enable: false
    version: "9.3.0"
# PLUGINS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# PAGE TEMPLATES >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
page_templates:
  friends_column: 2
  tags_style: blur
# PAGE TEMPLATES <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# CDN >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
cdn:
  enable: true
  provider: npmmirror
  custom_url:
# CDN <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# DEVELOPER MODE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
developer:
  enable: false
# DEVELOPER MODE <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end
